apiVersion: v1                       
kind: Service                        
metadata:                            
 name: {{ .Values.appname }}-language
 labels:
   app: {{ .Values.appname }}
   component: language
spec:                                
 type: ClusterIP 
 selector:                          
   app: {{ .Values.appname }}
   component: language
 ports:                             
   - name:                      
     port: 8007
     targetPort: 8007