apiVersion: v1                       
kind: Service                        
metadata:                            
 name: {{ .Values.appname }}-mongodb
 labels:
   app: {{ .Values.appname }}
   component: mongodb
spec:                                
 type: ClusterIP 
 selector:                          
   app: {{ .Values.appname }}
   component: mongodb
 ports:                             
   - name:                      
     port: {{ .Values.mongodbSettings.port }}
     targetPort: 27017