apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}-fx
  labels:
    app: {{ .Values.appname }}
    component: fx
spec:
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
        component: fx
    spec:
      imagePullSecrets:
      - name: public.repo.moovit24.de
      volumes: {{ include "common.storage.configureAppVolumes" .Values | nindent 8 }}
      {{ range $index, $hostPathConfiguration := .Values.extraAppVolumeMounts }}
        - name: extrappvolume-{{ $index }}
          hostPath:
            path: {{ $hostPathConfiguration.hostPath }}
      {{ end }}      
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "{{ .Values.appname }}-fx"
      containers:
      - name: {{ .Values.appname }}-fx
        image: "{{ .Values.images.mcp_fx.name }}:{{ .Values.images.mcp_fx.version }}"
        imagePullPolicy: {{ .Values.images.mcp_fx.pullPolicy }}
        volumeMounts: {{ include "common.storage.configureAppVolumeMountsInContainer" .Values | nindent 12 }}
          {{ range $index, $hostPathConfiguration := .Values.extraAppVolumeMounts }}
            - name: extrappvolume-{{ $index }}
              mountPath: {{ $hostPathConfiguration.mountPath }}
          {{ end }}    
        resources: 
{{- include "containerResources" . | indent 10 }}        
{{- include "helmut.args" . | indent 8 }}        
        env:
        - name: parameters
          value: |-           
{{- include "helmut.env" . | indent 12}}
