apiVersion: v1                       
kind: Service                        
metadata:                            
 name: {{ .Values.appname }}-web
 labels:
   app: {{ .Values.appname }}
   component: web
spec:                                
 type: ClusterIP 
 selector:                          
   app: {{ .Values.appname }}
   component: web
 ports:                             
   - name:                      
     port: 8080
     targetPort: 8080