apiVersion: v1                       
kind: Service                        
metadata:                            
 name: {{ .Values.appname }}-io
 labels:
   app: {{ .Values.appname }}
   component: io
spec:                                
 type: ClusterIP 
 selector:                          
   app: {{ .Values.appname }}
   component: io
 ports:                             
   - name:                      
     port: 8102
     targetPort: 8102