apiVersion: v1                       
kind: Service                        
metadata:                            
 name: {{ .Values.appname }}-streams
 labels:
   app: {{ .Values.appname }}
   component: streams
spec:                                
 type: ClusterIP 
 selector:                          
   app: {{ .Values.appname }}
   component: streams
 ports:                             
   - name:                      
     port: 8001
     targetPort: 8001