apiVersion: v1                       
kind: Service                        
metadata:                            
 name: {{ .Values.appname }}-users
 labels:
   app: {{ .Values.appname }}
   component: users
spec:                                
 type: ClusterIP 
 selector:                          
   app: {{ .Values.appname }}
   component: users
 ports:                             
   - name:                      
     port: 8000
     targetPort: 8000