apiVersion: v1                       
kind: Service                        
metadata:                            
 name: {{ .Values.appname }}-cronjob
 labels:
   app: {{ .Values.appname }}
   component: cronjob
spec:                                
 type: ClusterIP 
 selector:                          
   app: {{ .Values.appname }}
   component: cronjob
 ports:                             
   - name:                      
     port: 8008
     targetPort: 8008