apiVersion: v1                       
kind: Service                        
metadata:                            
 name: {{ .Values.appname }}-panel
 labels:
   app: {{ .Values.appname }}
   component: panel
spec:                                
 type: ClusterIP 
 selector:                          
   app: {{ .Values.appname }}
   component: panel
 ports:                             
   - name:                      
     port: 8081
     targetPort: 8081