apiVersion: v1                       
kind: Service                        
metadata:                            
 name: {{ .Values.appname }}-co
 labels:
   app: {{ .Values.appname }}
   component: co
spec:                                
 type: ClusterIP 
 selector:                          
   app: {{ .Values.appname }}
   component: co
 ports:                             
   - name:                      
     port: 8101
     targetPort: 8101