apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}-license
  labels:
    app: {{ .Values.appname }}
    component: license
spec:
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
        component: license
    spec:
      imagePullSecrets:
      - name: public.repo.moovit24.de
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "{{ .Values.appname }}-license"            
      containers:
      - name: {{ .Values.appname }}-license
        image: "{{ .Values.images.mcc_license.name }}:{{ .Values.images.mcc_license.version }}"
        imagePullPolicy: {{ .Values.images.mcc_license.pullPolicy }}
        resources: 
{{- include "containerResources" . | indent 10 }}        
{{- include "helmut.args" . | indent 8 }}        
        env:
        - name: parameters
          value: |-           
{{- include "helmut.env" . | indent 12}}