apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}-license
  labels:
    app: {{ .Values.appname }}
    component: license
spec:
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
        component: license
    spec:
      imagePullSecrets:
      - name: public.repo.moovit24.de
      volumes: {{ include "common.storage.configureAppVolumes" .Values | nindent 8 }}
      {{ range $index, $hostPathConfiguration := .Values.extraAppVolumeMounts }}
        - name: homefolder-1
          hostPath:
            path: {{ .Values.extraAppVolumeMountsSnapshotVersion.hostPath }}
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "{{ .Values.appname }}-license"            
      containers:
      - name: {{ .Values.appname }}-license
        image: "{{ .Values.images.mcc_license.name }}:{{ .Values.images.mcc_license.version }}"
        imagePullPolicy: {{ .Values.images.mcc_license.pullPolicy }}
        volumeMounts: {{ include "common.storage.configureAppVolumeMountsInContainer" .Values | nindent 12 }}
        - name: homefolder-1
          mountPath: "/version"
        resources: 
{{- include "containerResources" . | indent 10 }}        
{{- include "helmut.args" . | indent 8 }}        
        env:
        - name: parameters
          value: |-
{{- include "helmut.env" . | indent 12 }}
