apiVersion: v1                       
kind: Service                        
metadata:                            
 name: {{ .Values.appname }}-metadata
 labels:
   app: {{ .Values.appname }}
   component: metadata
spec:                                
 type: ClusterIP 
 selector:                          
   app: {{ .Values.appname }}
   component: metadata
 ports:                             
   - name:                      
     port: 8003
     targetPort: 8003