apiVersion: v1                       
kind: Service                        
metadata:                            
 name: {{ .Values.appname }}-mongoadmin
 labels:
   app: {{ .Values.appname }}
   component: mongoadmin
spec:                                
 type: ClusterIP 
 selector:                          
   app: {{ .Values.appname }}
   component: mongoadmin
 ports:                             
   - name:                      
     port: 8199
     targetPort: 8199