apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}-web
  labels:
    app: {{ .Values.appname }}
    component: web
spec:
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
        component: web
    spec:
      imagePullSecrets:
      - name: public.repo.moovit24.de
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "{{ .Values.appname }}-web"            
      containers:
      - name: {{ .Values.appname }}-web
        image: "{{ .Values.images.mcp_hw.name }}:{{ .Values.images.mcp_hw.version }}"
        imagePullPolicy: {{ .Values.images.mcp_hw.pullPolicy }}
        resources: 
{{- include "containerResources" . | indent 10 }}